### ISSUE TITLE
Use a JLL package

### ISSUE THREAD

**Issue by aviks** [tanmaykm/Openresty.jl#8]
This still seems to use a separate builder repo and use a `build.jl`. 

cc: @tanmaykm

**Comment by tanmaykm** [comment]
Yes, need to move to a JLL. I think we have one: https://github.com/JuliaPackaging/Yggdrasil/tree/master/O/Openresty - but I don't see the corresponding jll package. It may need some updates.

**Comment by aviks** [comment]
We should have the jll now

**Comment by tanmaykm** [comment]
jll registration seems to have failed again... will give it a look now
